remote_theme: eliottvincent/bay

header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Code  # <-- blog.md
    - name: Team  # <-- whatever.md

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: eva.robillard@ens-paris-saclay.fr
      link: mailto:eva.robillard@ens-paris-saclay.fr
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/eva-robillard
