

title: Nets-Within-Nets 2023
logo: image_2023-10-26_145028978.png
description: Sofia Hustiu, Eva Robillard, Joaquin Ezpeleta, Cristian Mahulea, Marius Kloetzer
show_downloads: false
google_analytics:
theme: just_the_docs
