

title: Nets-Within-Nets 2023
logo: /assets/img/logo.png
description: This website holds the material used in order to simulate the work of the article
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
